/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SavedIndexImport } from './routes/saved/index'
import { Route as FirstStepIndexImport } from './routes/first-step/index'
import { Route as EditorIndexImport } from './routes/editor/index'
import { Route as CvTemplatesIndexImport } from './routes/cv-templates/index'
import { Route as CvCreatorIndexImport } from './routes/cv-creator/index'
import { Route as CoverLetterIndexImport } from './routes/cover-letter/index'
import { Route as CoverLetterCreatorIndexImport } from './routes/cover-letter-creator/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SavedIndexRoute = SavedIndexImport.update({
  path: '/saved/',
  getParentRoute: () => rootRoute,
} as any)

const FirstStepIndexRoute = FirstStepIndexImport.update({
  path: '/first-step/',
  getParentRoute: () => rootRoute,
} as any)

const EditorIndexRoute = EditorIndexImport.update({
  path: '/editor/',
  getParentRoute: () => rootRoute,
} as any)

const CvTemplatesIndexRoute = CvTemplatesIndexImport.update({
  path: '/cv-templates/',
  getParentRoute: () => rootRoute,
} as any)

const CvCreatorIndexRoute = CvCreatorIndexImport.update({
  path: '/cv-creator/',
  getParentRoute: () => rootRoute,
} as any)

const CoverLetterIndexRoute = CoverLetterIndexImport.update({
  path: '/cover-letter/',
  getParentRoute: () => rootRoute,
} as any)

const CoverLetterCreatorIndexRoute = CoverLetterCreatorIndexImport.update({
  path: '/cover-letter-creator/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cover-letter-creator/': {
      id: '/cover-letter-creator/'
      path: '/cover-letter-creator'
      fullPath: '/cover-letter-creator'
      preLoaderRoute: typeof CoverLetterCreatorIndexImport
      parentRoute: typeof rootRoute
    }
    '/cover-letter/': {
      id: '/cover-letter/'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof CoverLetterIndexImport
      parentRoute: typeof rootRoute
    }
    '/cv-creator/': {
      id: '/cv-creator/'
      path: '/cv-creator'
      fullPath: '/cv-creator'
      preLoaderRoute: typeof CvCreatorIndexImport
      parentRoute: typeof rootRoute
    }
    '/cv-templates/': {
      id: '/cv-templates/'
      path: '/cv-templates'
      fullPath: '/cv-templates'
      preLoaderRoute: typeof CvTemplatesIndexImport
      parentRoute: typeof rootRoute
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorIndexImport
      parentRoute: typeof rootRoute
    }
    '/first-step/': {
      id: '/first-step/'
      path: '/first-step'
      fullPath: '/first-step'
      preLoaderRoute: typeof FirstStepIndexImport
      parentRoute: typeof rootRoute
    }
    '/saved/': {
      id: '/saved/'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/cover-letter-creator': typeof CoverLetterCreatorIndexRoute
  '/cover-letter': typeof CoverLetterIndexRoute
  '/cv-creator': typeof CvCreatorIndexRoute
  '/cv-templates': typeof CvTemplatesIndexRoute
  '/editor': typeof EditorIndexRoute
  '/first-step': typeof FirstStepIndexRoute
  '/saved': typeof SavedIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/cover-letter-creator': typeof CoverLetterCreatorIndexRoute
  '/cover-letter': typeof CoverLetterIndexRoute
  '/cv-creator': typeof CvCreatorIndexRoute
  '/cv-templates': typeof CvTemplatesIndexRoute
  '/editor': typeof EditorIndexRoute
  '/first-step': typeof FirstStepIndexRoute
  '/saved': typeof SavedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/cover-letter-creator/': typeof CoverLetterCreatorIndexRoute
  '/cover-letter/': typeof CoverLetterIndexRoute
  '/cv-creator/': typeof CvCreatorIndexRoute
  '/cv-templates/': typeof CvTemplatesIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/first-step/': typeof FirstStepIndexRoute
  '/saved/': typeof SavedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cover-letter-creator'
    | '/cover-letter'
    | '/cv-creator'
    | '/cv-templates'
    | '/editor'
    | '/first-step'
    | '/saved'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cover-letter-creator'
    | '/cover-letter'
    | '/cv-creator'
    | '/cv-templates'
    | '/editor'
    | '/first-step'
    | '/saved'
  id:
    | '__root__'
    | '/'
    | '/cover-letter-creator/'
    | '/cover-letter/'
    | '/cv-creator/'
    | '/cv-templates/'
    | '/editor/'
    | '/first-step/'
    | '/saved/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CoverLetterCreatorIndexRoute: typeof CoverLetterCreatorIndexRoute
  CoverLetterIndexRoute: typeof CoverLetterIndexRoute
  CvCreatorIndexRoute: typeof CvCreatorIndexRoute
  CvTemplatesIndexRoute: typeof CvTemplatesIndexRoute
  EditorIndexRoute: typeof EditorIndexRoute
  FirstStepIndexRoute: typeof FirstStepIndexRoute
  SavedIndexRoute: typeof SavedIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CoverLetterCreatorIndexRoute: CoverLetterCreatorIndexRoute,
  CoverLetterIndexRoute: CoverLetterIndexRoute,
  CvCreatorIndexRoute: CvCreatorIndexRoute,
  CvTemplatesIndexRoute: CvTemplatesIndexRoute,
  EditorIndexRoute: EditorIndexRoute,
  FirstStepIndexRoute: FirstStepIndexRoute,
  SavedIndexRoute: SavedIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cover-letter-creator/",
        "/cover-letter/",
        "/cv-creator/",
        "/cv-templates/",
        "/editor/",
        "/first-step/",
        "/saved/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/cover-letter-creator/": {
      "filePath": "cover-letter-creator/index.tsx"
    },
    "/cover-letter/": {
      "filePath": "cover-letter/index.tsx"
    },
    "/cv-creator/": {
      "filePath": "cv-creator/index.tsx"
    },
    "/cv-templates/": {
      "filePath": "cv-templates/index.tsx"
    },
    "/editor/": {
      "filePath": "editor/index.tsx"
    },
    "/first-step/": {
      "filePath": "first-step/index.tsx"
    },
    "/saved/": {
      "filePath": "saved/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
